---

   - name: run updates
     apt: update_cache=yes

   - name: Set MySQL root password before installing
     debconf: name='mysql-server-5.6' question='mysql-server/root_password' value='{{ mysql_root_password|quote }}' vtype='password'

   - name: Confirm MySQL root password before installing
     debconf: name='mysql-server-5.6' question='mysql-server/root_password_again' value='{{ mysql_root_password|quote }}' vtype='password'

   - name: install role pkgs
     apt: pkg={{ item }} state=latest force=yes update_cache=yes cache_valid_time=3600
     when: ansible_pkg_mgr == 'apt'
     with_items:
      - mysql-server-5.6
      - mysql-client-5.6
      - mysql-common-5.6
      - python-mysqldb

   - name: Deletes anonymous MySQL server user for localhost
     mysql_user: user="" state="absent" login_password="{{ mysql_root_password }}" login_user=root

   - name: Removes the MySQL test database
     mysql_db: db=test state=absent login_password="{{ mysql_root_password }}" login_user=root

   - name: Secures the MySQL root user
     mysql_user: user="root" password="{{ mysql_root_password }}" host="{{ item }}" login_password="{{ mysql_root_password }}" login_user=root
     with_items:
      - 127.0.0.1
      - localhost
      - ::1
      - "{{ ansible_fqdn }}"

   - name: copy my.cnf
     template: src="templates/my.cnf.j2" dest="/etc/mysql/my.cnf" owner=root group=root mode=0644

   - name: Copy .my.cnf file with root password credentials.
     template: src="templates/user-my.cnf.j2" dest="/root/.my.cnf" owner=root group=root mode=0600

   - name: ensure that mysql enabled
     service: name=mysql enabled=yes

   - name: ensure that mysql restarted
     service: name=mysql state=restarted

   - name: create magento database
     mysql_db: name={{ dbname }} state=present login_password="{{ mysql_root_password }}" login_user=root

   - name: create magento user
     mysql_user: name={{ dbuser }} password={{ upassword }} host={{ hostvars[item]['ansible_eth0']['ipv4']['address'] }} priv=mysql.proc:SELECT/{{ dbname }}.*:ALL login_password="{{ mysql_root_password }}" login_user=root state=present
     with_items:
      - "{{ groups['php'] }}"
      - "{{ groups['db'] }}"
