---

     - name: add web user
       user: name={{ web_user_name }} comment="Default Web User" uid={{ web_user_id }} group=admin

     - name: add php repo
       apt_repository: repo='ppa:ondrej/php5-5.6'
       when: ansible_distribution == 'Ubuntu'

     - name: run updates
       apt: update_cache=yes

     - name: install role pkgs
       apt: pkg={{ item }} state=latest
       when: ansible_pkg_mgr == 'apt'
       with_items:
        - php5
        - php5-fpm
        - php5-cli
        - php5-common
        - php5-dev
        - php5-curl
        - php5-gd
        - php5-intl
        - php5-mcrypt
        - php5-mysql
        - php-soap
        - php5-xsl
        - php5-mhash
        - nfs-common

     - name: create needed dirs
       file: path=/home/{{ web_user_name }}/{{ item }} state=directory owner={{ web_user_name }} group=admin mode=0755
       with_items:
         - public_html
         - logs
         - tmp

     - name: add mounts into fstab
       lineinfile: dest=/etc/fstab line="{{ hostvars['main']['ansible_eth0']['ipv4']['address'] }}:/home/{{ web_user_name }}/{{ item }}    /home/{{ web_user_name }}/{{ item }}   nfs auto,noatime,nolock,bg,nfsvers=4,intr,tcp,actimeo=1800 0 0"
       with_items:
         - public_html
         - logs
         - tmp

     - name: mount shares
       shell: mount -a

     - name: create php-fpm config
       template: src=templates/php-fpm.conf.j2 dest=/etc/php5/fpm/pool.d/www.conf owner=root group=root mode=0644
       notify: restart php-fpm

     - name: start and enable php-fpm
       service: name=php5-fpm state=started enabled=yes
